In [2]:
import torch
import torch.nn as nn

In [5]:
# In these examples we work with one value, omitting the batch size
# Here is a normal attention implementation
query = torch.tensor([[1, 2],
                      [1, 2]])
keys = torch.tensor([[0, 1], 
                     [1, 1]])

energy = torch.einsum("qd,kd->qk", [query, keys])

print(energy.numpy())

[[2 3]
 [2 3]]


In [11]:
# Here is a multi-headed attention implementation
# We have a query vector of len 2 with 2 heads and an embed_dim of 4
query = torch.tensor([[[1, 2], [1, 3]], 
                      [[1, 2], [1, 3]]])
keys = torch.tensor([[[0, 1], [1, 0]], 
                     [[1, 1], [0, 0]]])

energy = torch.einsum("qhd,khd->hqk", [query, keys])

print(energy.numpy())

[[[2 3]
  [2 3]]

 [[1 0]
  [1 0]]]
